[package]
name = "middleware"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
serde = { version = "1.0.228", features = ["derive"] }
tower-http = { version = "0.6.6", features = ["cors"] }
