[package]
name = "oidc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
config = "0.15.18"
openidconnect = "4.0.1"
serde = { version = "1.0.228", features = ["derive"] }
utoipa = "5.4.0"
